/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MapRouteImport } from './routes/map'
import { Route as DataRouteImport } from './routes/data'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAiScenarioRouteImport } from './routes/api/public/ai-scenario'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiScenarioRoute = ApiPublicAiScenarioRouteImport.update({
  id: '/api/public/ai-scenario',
  path: '/api/public/ai-scenario',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/data': typeof DataRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/api/public/ai-scenario': typeof ApiPublicAiScenarioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/data': typeof DataRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/api/public/ai-scenario': typeof ApiPublicAiScenarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/data': typeof DataRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/api/public/ai-scenario': typeof ApiPublicAiScenarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/data'
    | '/map'
    | '/reports'
    | '/api/public/ai-scenario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/data'
    | '/map'
    | '/reports'
    | '/api/public/ai-scenario'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/data'
    | '/map'
    | '/reports'
    | '/api/public/ai-scenario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  DataRoute: typeof DataRoute
  MapRoute: typeof MapRoute
  ReportsRoute: typeof ReportsRoute
  ApiPublicAiScenarioRoute: typeof ApiPublicAiScenarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-scenario': {
      id: '/api/public/ai-scenario'
      path: '/api/public/ai-scenario'
      fullPath: '/api/public/ai-scenario'
      preLoaderRoute: typeof ApiPublicAiScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  DataRoute: DataRoute,
  MapRoute: MapRoute,
  ReportsRoute: ReportsRoute,
  ApiPublicAiScenarioRoute: ApiPublicAiScenarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
