/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YieldRouteImport } from './routes/yield'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'

const YieldRoute = YieldRouteImport.update({
  id: '/yield',
  path: '/yield',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/exports': typeof ExportsRoute
  '/monitoring': typeof MonitoringRoute
  '/planning': typeof PlanningRoute
  '/reports': typeof ReportsRoute
  '/yield': typeof YieldRoute
  '/api/assistant': typeof ApiAssistantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/exports': typeof ExportsRoute
  '/monitoring': typeof MonitoringRoute
  '/planning': typeof PlanningRoute
  '/reports': typeof ReportsRoute
  '/yield': typeof YieldRoute
  '/api/assistant': typeof ApiAssistantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/exports': typeof ExportsRoute
  '/monitoring': typeof MonitoringRoute
  '/planning': typeof PlanningRoute
  '/reports': typeof ReportsRoute
  '/yield': typeof YieldRoute
  '/api/assistant': typeof ApiAssistantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/assistant'
    | '/dashboard'
    | '/exports'
    | '/monitoring'
    | '/planning'
    | '/reports'
    | '/yield'
    | '/api/assistant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/assistant'
    | '/dashboard'
    | '/exports'
    | '/monitoring'
    | '/planning'
    | '/reports'
    | '/yield'
    | '/api/assistant'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/assistant'
    | '/dashboard'
    | '/exports'
    | '/monitoring'
    | '/planning'
    | '/reports'
    | '/yield'
    | '/api/assistant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AssistantRoute: typeof AssistantRoute
  DashboardRoute: typeof DashboardRoute
  ExportsRoute: typeof ExportsRoute
  MonitoringRoute: typeof MonitoringRoute
  PlanningRoute: typeof PlanningRoute
  ReportsRoute: typeof ReportsRoute
  YieldRoute: typeof YieldRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yield': {
      id: '/yield'
      path: '/yield'
      fullPath: '/yield'
      preLoaderRoute: typeof YieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AssistantRoute: AssistantRoute,
  DashboardRoute: DashboardRoute,
  ExportsRoute: ExportsRoute,
  MonitoringRoute: MonitoringRoute,
  PlanningRoute: PlanningRoute,
  ReportsRoute: ReportsRoute,
  YieldRoute: YieldRoute,
  ApiAssistantRoute: ApiAssistantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
